"""Persistent storage for the Excel workbook.

Backends
  local       A directory on a persistent volume (Hugging Face persistent
              storage mounts at /data). Writes are atomic (temp file + rename)
              and the previous version is kept as <name>.bak.
  s3          Any S3-compatible bucket (AWS S3, Cloudflare R2, Backblaze B2,
              MinIO). Versioning on the bucket is recommended.
  hf_dataset  A private Hugging Face dataset repository. Every save is a
              commit, so the full version history is kept by the Hub.
"""
from __future__ import annotations

import asyncio
import logging
import os
import shutil
import tempfile
from pathlib import Path

from ..config import Settings, get_settings

log = logging.getLogger(__name__)


class StorageError(Exception):
    pass


class StorageService:
    name = "base"
    persistent = True

    async def download(self, filename: str, dest: Path) -> bool:  # pragma: no cover - interface
        raise NotImplementedError

    async def upload(self, src: Path, filename: str) -> None:  # pragma: no cover - interface
        raise NotImplementedError

    def describe(self) -> dict:  # pragma: no cover - interface
        raise NotImplementedError

    # Small binary objects (stored Lighthouse reports). Keys are generated by the
    # server only, e.g. "reports/2026/10/123-mobile.json.gz".
    async def put_object(self, key: str, data: bytes) -> None:  # pragma: no cover - interface
        raise NotImplementedError

    async def get_object(self, key: str) -> bytes | None:  # pragma: no cover - interface
        raise NotImplementedError

    async def delete_objects(self, keys: list[str]) -> None:  # pragma: no cover - interface
        raise NotImplementedError


def _safe_key(key: str) -> str:
    parts = key.replace("\\", "/").split("/")
    if not key or key.startswith("/") or any(p in ("", ".", "..") for p in parts):
        raise StorageError(f"Invalid object key {key!r}")
    return "/".join(parts)


class LocalStorage(StorageService):
    name = "local"

    def __init__(self, directory: str):
        self.directory = Path(directory)

    @property
    def persistent(self) -> bool:  # type: ignore[override]
        # /data is the Hugging Face persistent-storage mount point; it only exists when
        # persistent storage is enabled. Docker volumes can opt in explicitly.
        # Read through Settings so values from the .env file count too (not only real env vars).
        if get_settings().storage_local_is_persistent:
            return True
        data = Path("/data")
        under_data = self.directory.as_posix() == "/data" or self.directory.as_posix().startswith("/data/")
        return under_data and data.is_dir() and os.access(data, os.W_OK)

    def _path(self, filename: str) -> Path:
        return self.directory / filename

    async def download(self, filename: str, dest: Path) -> bool:
        src = self._path(filename)
        if not src.exists():
            return False
        await asyncio.to_thread(shutil.copy2, src, dest)
        return True

    async def upload(self, src: Path, filename: str) -> None:
        def _write() -> None:
            self.directory.mkdir(parents=True, exist_ok=True)
            target = self._path(filename)
            tmp = self.directory / f".{filename}.{os.getpid()}.tmp"
            shutil.copy2(src, tmp)
            with open(tmp, "r+b") as fh:  # fsync needs a writable handle on some platforms
                os.fsync(fh.fileno())
            if target.exists():
                shutil.copy2(target, self.directory / f"{filename}.bak")
            os.replace(tmp, target)

        try:
            await asyncio.to_thread(_write)
        except OSError as exc:
            raise StorageError(f"Could not write {filename} to {self.directory}: {exc}") from exc

    async def put_object(self, key: str, data: bytes) -> None:
        target = self.directory / _safe_key(key)

        def _write() -> None:
            target.parent.mkdir(parents=True, exist_ok=True)
            tmp = target.with_name(f".{target.name}.{os.getpid()}.tmp")
            tmp.write_bytes(data)
            os.replace(tmp, target)

        try:
            await asyncio.to_thread(_write)
        except OSError as exc:
            raise StorageError(f"Could not write {key}: {exc}") from exc

    async def get_object(self, key: str) -> bytes | None:
        target = self.directory / _safe_key(key)
        return await asyncio.to_thread(lambda: target.read_bytes() if target.is_file() else None)

    async def delete_objects(self, keys: list[str]) -> None:
        def _rm() -> None:
            for k in keys:
                (self.directory / _safe_key(k)).unlink(missing_ok=True)

        await asyncio.to_thread(_rm)

    def describe(self) -> dict:
        return {
            "backend": "local",
            "location": str(self._path(get_settings().excel_filename)),
            "persistent": self.persistent,
            "warning": None if self.persistent else (
                "Excel is NOT on persistent storage and would be lost on restart. On Hugging Face enable "
                "persistent storage (mounted at /data) or set STORAGE_BACKEND to hf_dataset or s3. "
                "(For a Docker volume set STORAGE_LOCAL_IS_PERSISTENT=true.)"
            ),
        }


class S3Storage(StorageService):
    name = "s3"

    def __init__(self, s: Settings):
        if not s.s3_bucket:
            raise StorageError("S3_BUCKET is required for STORAGE_BACKEND=s3")
        import boto3

        self.bucket = s.s3_bucket
        self.prefix = s.s3_prefix.strip("/")
        self.client = boto3.client(
            "s3",
            endpoint_url=s.s3_endpoint_url or None,
            region_name=s.s3_region or None,
            aws_access_key_id=s.aws_access_key_id or None,
            aws_secret_access_key=s.aws_secret_access_key or None,
        )

    def _key(self, filename: str) -> str:
        return f"{self.prefix}/{filename}" if self.prefix else filename

    async def download(self, filename: str, dest: Path) -> bool:
        from botocore.exceptions import ClientError

        def _get() -> bool:
            try:
                self.client.download_file(self.bucket, self._key(filename), str(dest))
                return True
            except ClientError as exc:
                code = str(exc.response.get("Error", {}).get("Code", ""))
                if code in ("404", "NoSuchKey", "NotFound"):
                    return False
                raise StorageError(f"S3 download failed: {code}") from exc

        return await asyncio.to_thread(_get)

    async def upload(self, src: Path, filename: str) -> None:
        def _put() -> None:
            try:
                self.client.upload_file(
                    str(src), self.bucket, self._key(filename),
                    ExtraArgs={"ContentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                )
            except Exception as exc:  # botocore raises many types
                raise StorageError(f"S3 upload failed: {type(exc).__name__}") from exc

        await asyncio.to_thread(_put)

    async def put_object(self, key: str, data: bytes) -> None:
        def _put() -> None:
            try:
                self.client.put_object(Bucket=self.bucket, Key=self._key(_safe_key(key)), Body=data,
                                       ContentType="application/gzip")
            except Exception as exc:  # noqa: BLE001
                raise StorageError(f"S3 upload failed: {type(exc).__name__}") from exc

        await asyncio.to_thread(_put)

    async def get_object(self, key: str) -> bytes | None:
        from botocore.exceptions import ClientError

        def _get() -> bytes | None:
            try:
                return self.client.get_object(Bucket=self.bucket, Key=self._key(_safe_key(key)))["Body"].read()
            except ClientError as exc:
                if str(exc.response.get("Error", {}).get("Code", "")) in ("404", "NoSuchKey", "NotFound"):
                    return None
                raise StorageError("S3 download failed") from exc

        return await asyncio.to_thread(_get)

    async def delete_objects(self, keys: list[str]) -> None:
        def _del() -> None:
            for i in range(0, len(keys), 1000):
                self.client.delete_objects(Bucket=self.bucket, Delete={
                    "Objects": [{"Key": self._key(_safe_key(k))} for k in keys[i:i + 1000]], "Quiet": True})

        await asyncio.to_thread(_del)

    def describe(self) -> dict:
        return {"backend": "s3", "location": f"s3://{self.bucket}/{self._key(get_settings().excel_filename)}",
                "persistent": True, "warning": None}


class HFDatasetStorage(StorageService):
    name = "hf_dataset"

    def __init__(self, s: Settings):
        if not (s.hf_token and s.hf_dataset_repo):
            raise StorageError("HF_TOKEN and HF_DATASET_REPO are required for STORAGE_BACKEND=hf_dataset")
        from huggingface_hub import HfApi

        self.api = HfApi(token=s.hf_token)
        self.repo = s.hf_dataset_repo
        self.prefix = s.hf_dataset_path.strip("/")
        self.token = s.hf_token

    def _path(self, filename: str) -> str:
        return f"{self.prefix}/{filename}" if self.prefix else filename

    async def download(self, filename: str, dest: Path) -> bool:
        from huggingface_hub.errors import EntryNotFoundError, RemoteEntryNotFoundError  # type: ignore[attr-defined]

        def _get() -> bool:
            with tempfile.TemporaryDirectory() as tmp:
                try:
                    p = self.api.hf_hub_download(
                        repo_id=self.repo, filename=self._path(filename), repo_type="dataset",
                        local_dir=tmp, force_download=True,
                    )
                except (EntryNotFoundError, RemoteEntryNotFoundError):
                    return False
                except Exception as exc:
                    raise StorageError(f"Hugging Face dataset download failed: {type(exc).__name__}: "
                                       f"{str(exc).replace(self.token, '***')[:300]}") from exc
                shutil.copy2(p, dest)
                return True

        return await asyncio.to_thread(_get)

    async def upload(self, src: Path, filename: str) -> None:
        def _put() -> None:
            try:
                self.api.upload_file(
                    path_or_fileobj=str(src), path_in_repo=self._path(filename), repo_id=self.repo,
                    repo_type="dataset", commit_message=f"Update {filename}",
                )
            except Exception as exc:
                raise StorageError(f"Hugging Face dataset upload failed: {type(exc).__name__}: "
                                   f"{str(exc).replace(self.token, '***')[:300]}") from exc

        await asyncio.to_thread(_put)

    async def put_object(self, key: str, data: bytes) -> None:
        def _put() -> None:
            try:
                self.api.upload_file(path_or_fileobj=data, path_in_repo=self._path(_safe_key(key)), repo_id=self.repo,
                                     repo_type="dataset", commit_message="Add Lighthouse report")
            except Exception as exc:  # noqa: BLE001
                raise StorageError(f"Hugging Face dataset upload failed: {type(exc).__name__}") from exc

        await asyncio.to_thread(_put)

    async def get_object(self, key: str) -> bytes | None:
        with tempfile.TemporaryDirectory() as tmp:
            dest = Path(tmp) / "obj"
            ok = await self.download(_safe_key(key), dest)
            return dest.read_bytes() if ok else None

    async def delete_objects(self, keys: list[str]) -> None:
        from huggingface_hub import CommitOperationDelete

        def _del() -> None:
            for i in range(0, len(keys), 500):  # one commit per batch
                ops = [CommitOperationDelete(path_in_repo=self._path(_safe_key(k))) for k in keys[i:i + 500]]
                try:
                    self.api.create_commit(repo_id=self.repo, repo_type="dataset", operations=ops,
                                           commit_message="Remove expired Lighthouse reports")
                except Exception as exc:  # noqa: BLE001 - files may already be gone
                    log.warning("HF delete batch failed: %s", type(exc).__name__)

        await asyncio.to_thread(_del)

    def describe(self) -> dict:
        return {"backend": "hf_dataset",
                "location": f"hf://datasets/{self.repo}/{self._path(get_settings().excel_filename)}",
                "persistent": True, "warning": None}


_storage: StorageService | None = None


def get_storage() -> StorageService:
    global _storage
    if _storage is None:
        s = get_settings()
        if s.storage_backend == "s3":
            _storage = S3Storage(s)
        elif s.storage_backend == "hf_dataset":
            _storage = HFDatasetStorage(s)
        else:
            _storage = LocalStorage(s.local_storage_dir)
    return _storage


def set_storage(storage: StorageService | None) -> None:
    global _storage
    _storage = storage
